Add example systemd service
donatj/hookah pull request #2
Opened 2017-05-14 19:02 UTC by Cretezy

2017-05-15 02:58 UTC, donatj commented
Thank you so much for the contribution! I don't personally know much at all about Systemd so I'm going to run this by a friend who does. So you think this should be linked or directly in the README?

2017-05-18 04:20 UTC, donatj requested changes

2017-05-18 04:20 UTC, donatj commented on hookah.service
> +ExecStart=/bin/bash -c "$GOPATH/bin/hookah --server-root $HOME/hooks --http-port 8808"
As I don't wish to make Hookah specific to Go users, could we change the example binary path to `/usr/local/bin/hookah`.  My friend wasn't 100% certain $HOME would work from systemd like this? Can you validate this? I think my preference either way would be to also change the server root to maybe `/root/hooks`?

Thoughts?

2017-05-18 14:12 UTC, Cretezy commented
$HOME works for user services, which is what hookah should be ran as. In theory we shouldn't run it as root for security.

2018-04-24 15:55 UTC, donatj commented
I'm closing this. If you're still interested you could throw it in the Wiki - https://github.com/donatj/hookah/wiki

2019-05-03 17:16 UTC, closed without merging